### ISSUE TITLE
Allow custom snooze duration

### ISSUE THREAD

**Issue by Morpheus0x** [gabeg805/NFC-Alarm-Clock#1]
Please allow for custom snooze duration. 

I would like to set something between 5 and 10 minutes, but it would be great if the user could input a custom number of minutes.

**Comment by gabeg805** [comment]
Hi Morpheus, sorry it took me so long to see this!  I can definitely allow for snooze durations in between 5-10 minutes.  I'll add that to one of the next updates

**Comment by gabeg805** [comment]
Hi @Morpheus0x, this should be possible in the latest version, 12.1.0!  I just added numbers between 5-10, but I didn't make it so that a custom number could be entered.
