### ISSUE TITLE
Support Direct Boot

### ISSUE THREAD

**Issue by secretmango** [gabeg805/NFC-Alarm-Clock#10]
[More info in this comment](https://github.com/yuriykulikov/AlarmClock/issues/398)

Some clocks like the AOSP one or [new-clock](https://github.com/qw123wh/new-clock) support direct boot.

This is relevant on GrapheneOS with automatic reboot, or when OS updates cause an immediate reboot. This is normally no problem, unless an alarm clock then stops working.

Rebooting clears the encryption key from RAM which may be wanted.

**Comment by gabeg805** [comment]
I just implemented this, but I still need to test it.  If all goes well, it will be in the next release.

**Comment by secretmango** [comment]
wonderful!
