### ISSUE TITLE
Latest version release missing

### ISSUE THREAD

**Issue by Camo30** [gabeg805/NFC-Alarm-Clock#17]
Hello,

When using Google Play to search for your app the current version is 12.3.1 while when using Izzy it is stuck at 12.3.0. I've installed it from Izzy and because of this Google Play notifies me every few days about an update which can't be applied. Could you please push the latest release additionally to Izzy? Thanks

https://play.google.com/store/apps/details?id=com.nfcalarmclock -> 12.3.1
https://apt.izzysoft.de/fdroid/index/apk/com.nfcalarmclock -> 12.3.0

**Comment by gabeg805** [comment]
Sorry about that @Camo30!  I just published the release of v12.3.1.  I think Izzy automatically gets it from here, so they should have it soon.  Thanks for letting me know!
