### ISSUE TITLE
APK download

### ISSUE THREAD

**Issue by IzzySoft** [gabeg805/NFC-Alarm-Clock#2]
Are there any plans to make this FOSS app available outside of Google's walled garden for those without access there? E.g. attaching it to your [tagged releases](https://github.com/gabeg805/NFC-Alarm-Clock/releases), or bringing it to [F-Droid](https://f-droid.org/) (would require a build flavor coming without the proprietary `com.google.android.play:core`)?

**Comment by BloodRaven0** [comment]
+1 would love to see this app on F-Droid or IzzyOnDroid repos without google bloat.

**Comment by IzzySoft** [comment]
Any word, @gabeg805?

**Comment by gabeg805** [comment]
Sorry I just saw this! Yeah I can try to do that. Shoot, I just added Google's In App billing system which uses that dependency you mentioned. I should be able to make a version without it though. I'll add this to my TODO list. Thanks for the suggestion!

**Comment by IzzySoft** [comment]
@gabeg805 ouch, that billing library would be another culprit. I might preaching the choir here, but maybe setting up build flavors is an option – having `gplay` for PlayStore and e.g. `foss` or `libre` for the variant sticking entirely with F/LOSS code?

**Comment by gabeg805** [comment]
It's no problem! I only use those dependencies so that people can support development and the Google Billing system was just theeasiest way to facilitate that. I can always remove that small part though.

**Comment by IzzySoft** [comment]
> I can always remove that small part though.

At least for the libre variant, that would be great. Maybe then we can get the app even to F-Droid.org (and not just to [my repo](https://apt.izzysoft.de/fdroid). Please let me know when such an APK is available, so I can run it through one of the checkes used at F-Droid.org.

**Comment by gabeg805** [comment]
Yeah I'll let you know! It'll probably be a couple weeks or so. I'm in the process of converting all the Java code to Kotlin, which will take me quite a bit of time because I want to make sure nothing is broken. Thanks for putting this on my radar!

**Comment by IzzySoft** [comment]
Great to read that – gladly done, and looking forward to your ping then. Wish you easy going and great success!

**Comment by gabeg805** [comment]
Hey @IzzySoft, I should be releasing a version within the next couple of days.  I just want to run a couple more day in the life tests, but I can also send you what I have now if you want to run your checks on it?  Or would you rather download it via me creating releases?  I just realized I've never done that for this app...sorry about that

Btw, I've never created build variants before so I would definitely want another set of eyes on it to make sure it works the way it should.  Do you want to do a cursory check of my app/build.gradle.kts file to make sure everything is squared away?  Or how do you want to go about checking that the app is F/LOSS compliant?

**Comment by IzzySoft** [comment]
> I can also send you what I have now if you want to run your checks on it?

Sure you can. You can e.g. attached it here to the issue (if that allows no `*.apk`, simply remane it to `.apk.zip`). I'll then let you know the scan results.

> Do you want to do a cursory check of my app/build.gradle.kts file

I'm no Android dev, so I could not tell if something's amiss, sorry.

> Or how do you want to go about checking that the app is F/LOSS compliant?

I'll have to go by the scan results.

**Comment by gabeg805** [comment]
No worries! I'll attach the apk once I get home from work.

**Comment by gabeg805** [comment]
Here's the apk!  Sorry it took so long, I was working out some kinks on a small bug I found when two alarms go off back to back.  This is still being tested, but it's very close to being finalized.

Like you said about the attachment, I had to add .zip to the end.  I didn't zip it though, so you can just remove the .zip at the and you should be in business.

[nfc_alarm_clock_v12.0.0-beta006-foss-release.apk.zip](https://github.com/gabeg805/NFC-Alarm-Clock/files/13422404/nfc_alarm_clock_v12.0.0-beta006-foss-release.apk.zip)

**Comment by IzzySoft** [comment]
Looks great! Here're the results from my library scanner:

```
Libraries detected:
-------------------
* Android Support v4 (/android/support/v4): Development Framework, Apache-2.0
* AndroidX Activity (/androidx/activity): Utility, Apache-2.0
* Android Jetpack Annotations (/androidx/annotation): Utility, Apache-2.0
* AppCompat (/androidx/appcompat): Utility, Apache-2.0
* Cardview (/androidx/cardview): UI Component, Apache-2.0
* Concurrent (/androidx/concurrent): Utility, Apache-2.0
* Constraint Layout Library (/androidx/constraintlayout): Utility, Apache-2.0
* Coordinatorlayout (/androidx/coordinatorlayout): UI Component, Apache-2.0
* Androidx Core (/androidx/core): Utility, Apache-2.0
* Databinding (/androidx/databinding): Utility, Apache-2.0
* Android Emoji2 Compat (/androidx/emoji2): UI Component, Apache-2.0
* AndroidX Fragment (/androidx/fragment): UI Component, Apache-2.0
* Lifecycle (/androidx/lifecycle): Utility, Apache-2.0
* Loader (/androidx/loader): Utility, Apache-2.0
* Preference (/androidx/preference): Utility, Apache-2.0
* ProfileInstaller (/androidx/profileinstaller): Utility, Apache-2.0
* Room (/androidx/room): Utility, Apache-2.0
* Recyclerview (/androidx/recyclerview): Utility, Apache-2.0
* Android Activity Saved State (/androidx/savedstate): Utility, Apache-2.0
* Startup (/androidx/startup): Utility, Apache-2.0
* Vectordrawable (/androidx/vectordrawable): UI Component, Apache-2.0
* Android Jetpack VersionedParcelable (/androidx/versionedparcelable): Utility, Apache-2.0
* AndroidX Widget ViewPager2 (/androidx/viewpager2): UI Component, Apache-2.0
* Google Material Design (/com/google/android/material): Utility, Apache-2.0
* Dagger (/dagger): Utility, Apache-2.0

No offending libs found.
```

So may I suggest you [tag your releases](https://github.com/gabeg805/NFC-Alarm-Clock/releases) from now on, and attach the APKs to their corresponding release tags, starting with the current/next one (the one I should pick up)? I'd then add it to my repo. If your app is listed on Play (IIRC it is), I'd take description and graphics from there (maybe with minor adjustments like e.g. formatting), and if you accept provide you that in Fastlane structure via PR, so you can control how your app is presented (you even can use fastlane *binaries* to deploy that to PlayStore if you wish – so "one ring to…" err, you know what I mean :wink:)

**Comment by IzzySoft** [comment]
[Repo Link](https://apt.izzysoft.de/packages/com.nfcalarmclock/) (will turn from 404 to 200 with the next sync around 5 pm UTC) :smile: THANKS!
