### ISSUE TITLE
Select/store nfc tags

### ISSUE THREAD

**Issue by straboti** [gabeg805/NFC-Alarm-Clock#4]
Hi! Could you make the app be able to store nfc tags used? I am using the app daily, and one problem I'm facing is the app forgetting the tag set after switching nfc off. It would be handy if when scanning an NFC tag, you would be able to name and store it, and could later use that instead of re-scanning the tag every time I set a new alarm.

**Comment by gabeg805** [comment]
Hi!  Sorry it took so long.  I was trying to figure out a decent way to do this.  This feature is available in v12.2.0
