### ISSUE TITLE
Maths based question answering to dismiss an alarm

### ISSUE THREAD

**Issue by advait404** [gabeg805/NFC-Alarm-Clock#8]
Firstly, thank a lot for the wonderful app. Currently I am using AMdroid, which has a nice feature where the user needs to answer one or more basic maths questions before they can dismiss the alarm. There's various options to configure the difficult of the questions, but I prefer it to be at a level where it's solvable but takes a little thinking to do so.

Eg:
12x5+11
18x3-7

Adding this feature would be nice, since it makes it harder to dismiss the alarm and makes you think more actively.

**Comment by gabeg805** [comment]
Hi @advait404, sorry I don't plan on adding this to the app.  When I was first designing the app, I considered doing something like this, but then realized, I didn't want to have some arbitrary math level that a person chooses and it outputs random math problems.  I just never really liked that vision, and at this point, I'd have to redesign so much to fit it into what the app is today.

I appreciate the suggestion, but I don't think I'll be doing this!

**Comment by kaanelloed** [comment]
Hi @gabeg805, just to be clear, you really don't want this feature or you will still consider adding it if someone makes a PR ?

**Comment by gabeg805** [comment]
Hi @kaanelloed, I really don't want this feature and so I'm not considering adding it.  As the app evolves...maybe, but for the time being (at least for the next idk year), I don't see myself working on this or adding it.
